updated actions

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -21,31 +21,31 @@ jobs:
       - name: LaTeX Action
         uses: xu-cheng/latex-action@v3
         with:
-          root_file: cv-lt.tex
-          extra_packages: texlive-fonts-extra bibentry natbib  # Added texlive-fonts-extra for potential font dependencies
+          root_file: cv-llt.tex
+          extra_packages: texlive-fonts-extra bibentry natbib cochineal cabin inconsolata  # Added font packages
           args: -pdf -file-line-error -interaction=nonstopmode
-          latexmk_use_lualatex: true  # Use LuaLaTeX for better font and package support
+          latexmk_use_lualatex: true  # Use LuaLaTeX for fontspec support
 
       # Debug step: Show LaTeX logs if compilation fails
       - name: Show LaTeX logs on failure
         if: failure()
         run: |
-          cat cv-lt.log || echo "Log file not found."
+          cat cv-llt.log || echo "Log file not found."
 
       # Upload artifact on push to master
       - name: Upload a Build Artifact
         if: github.event_name == 'push'
         uses: actions/upload-artifact@v4.4.3
         with:
-          name: cv-lt.pdf
-          path: cv-lt.pdf
+          name: cv-llt.pdf
+          path: cv-llt.pdf
 
       # Upload to GitHub Release if triggered by a release event
       - name: Upload resume to GitHub Release
         if: github.event_name == 'release'
         run: |
-          gh release upload ${{ github.event.release.tag_name }} cv-lt.pdf
-          gh release upload ${{ github.event.release.tag_name }} cv-lt.tex
+          gh release upload ${{ github.event.release.tag_name }} cv-llt.pdf
+          gh release upload ${{ github.event.release.tag_name }} cv-llt.tex
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -54,7 +54,7 @@ jobs:
         if: github.event_name == 'release'
         run: |
           mkdir -p ../gh-pages
-          mv cv-lt.pdf ../gh-pages/resume.pdf
+          mv cv-llt.pdf ../gh-pages/resume.pdf
           cp index.html ../gh-pages
 
       # Deploy to GitHub Pages during release
